#!/usr/bin/env ruby

require 'rbbt/workflow'
Workflow.require_workflow "Genomes1000"
require 'rbbt/sources/genomes1000'

claims = [Genomes1000.mutations, Genomes1000.rsids]

claims.each{|claim| claim.produce }

